<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit59ae6b5fd12ce399d8b0951bbedacc87
{
    public static $prefixLengthsPsr4 = array (
        'C' => 
        array (
            'CoffeeCode\\Uploader\\' => 20,
            'CoffeeCode\\Optimizer\\' => 21,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'CoffeeCode\\Uploader\\' => 
        array (
            0 => __DIR__ . '/..' . '/coffeecode/uploader/src',
        ),
        'CoffeeCode\\Optimizer\\' => 
        array (
            0 => __DIR__ . '/..' . '/coffeecode/optimizer/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit59ae6b5fd12ce399d8b0951bbedacc87::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit59ae6b5fd12ce399d8b0951bbedacc87::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
